### ISSUE TITLE
Replace this extension with custom browser CSS style

### ISSUE THREAD

**Issue by ssaunier** [Natim/trello-card-counter-addon#3]
Hi @Natim,

This is not really an issue with your code, just an alternative solution to your extension.

Thanks to your open-source extension code, I discovered that Trello was computing this information but hiding it by default!

We can replace your extension with some custom CSS code. Create a [`chrome/userContent.css`](http://superuser.com/questions/318912/how-to-override-the-css-of-a-site-in-firefox-with-usercontent-css) file in your Firefox profile and add this:

``` css
@-moz-document domain(trello.com) {
  .list-header-num-cards {
    display: block !important;
  }
}
```

This way the card counts automatically show up without any lag, no JS involved!

Cheers
